# Generated by Django 5.2.7 on 2025-11-23 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Friend Request Pending'), ('accepted', 'Friends'), ('rejected', 'Friend Request Rejected'), ('blocked', 'Blocked'), ('unblocked', 'Unblocked')], default='pending', max_length=10)),
                ('friend_since', models.DateField(blank=True, null=True)),
                ('blocked_since', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocks_initiated', to=settings.AUTH_USER_MODEL)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_initiated', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'relationships',
                'indexes': [models.Index(fields=['user1', 'status'], name='relationshi_user1_i_ceffa2_idx'), models.Index(fields=['user2', 'status'], name='relationshi_user2_i_4b2481_idx')],
                'unique_together': {('user1', 'user2')},
            },
        ),
    ]
